### ISSUE TITLE
【追加要望】ガード時の要素追加

### ISSUE THREAD

**Issue by MasatakaMorimoto** [TeamMorimoto/UnityGame_DragonSlayer#1]
現在のガードにプラス、遊びの検証用に別のガード手段を追加して欲しい

【追加要素】
・押したらガード発動とは別に、押し続けたらガード状態を継続を追加
・どちらかしか行えないようにする（スクリプタブルオブジェクト内でどちらを使うかを選択でき利用にする⇒チェックボックスかなにかで）
上記アクションに以下パラメータを持たす

●ガードずっと
・押しっぱなしの時の防御力
・ダメージを受けた際のスタミナ
・ガード状態になるまでの時間
・ガード状態（盾ボタンホールド）中はスタミナ回復しない

**Comment by konkon317** [comment]
1ce8dd9a58e1a712d4bc58df3f9121b617e12fde
で追加しました

@MasatakaMorimoto 
確認をよろしくお願いします

**Comment by konkon317** [comment]
86c1b1641527b6c749c4bdcd1b8cfbb24480d076

ちょっと追加

**Comment by MasatakaMorimoto** [comment]
ガード中スタミナ回復しないとかも実装されてる？

**Comment by konkon317** [comment]
確認したら防御開始時の消費スタミナを0にしてた
パラメータ上げてみたら、ちゃんと消費した後回復してた

継続防御の場合は最初に消費せずに防御が成立したときに消費するようにした方がいいかな

**Comment by konkon317** [comment]
ごめんなさい　
実装の要件しっかり把握してなかったみたいです

未実装のとこ作ります

**Comment by konkon317** [comment]
押しっぱなしができる行動って防御だけ？
他の行動で押しっぱなしができるなら、その際のスタミナ回復の有無はどう考えてる？

**Comment by konkon317** [comment]
fe2297c0c592c94f1354d30ae8a2f6c070b84908

取りあえずどの行動でも押しっぱなしをする場合はスタミナ回復しない形で作っておいた
防御だけに限定するとかもすぐできます。

**Comment by MasatakaMorimoto** [comment]
防御だけにしておいてー
実装はOK

**Comment by konkon317** [comment]
51182192b0b47a97616708b3be7047a715910f4d

押しっぱなしのスタミナ回復なしを　防御のみに限定しておきました
