### ISSUE TITLE
【追加要望】主人公の攻撃を三段階まで指定できるようにしたい

### ISSUE THREAD

**Issue by MasatakaMorimoto** [TeamMorimoto/UnityGame_DragonSlayer#6]
【概要】
主人公の攻撃行動を３コンボまで出来るようにしたい

【内容】
主人公の攻撃に二段階目、三段階目の指定もできるようにする
指定するパラメーターは現状の攻撃のものと同じ

ただし仕様的に、一段回目のダメージ計算が終わった後に入力を受け付けるようにする
※細かい仕様調整で、いつから入力受付するかを調整できるようにはするかもですが、一旦は考えない。

**Comment by konkon317** [comment]
三段階攻撃って、主人公のみの想定でしょうか？
多分、敵キャラクターもできた方がいいよね

**Comment by konkon317** [comment]
2f8cd4d260da0d55a5718cec7bd228cabb831987

が最新のブランチで実装しました
@MasatakaMorimoto
